# Cloudflare Workers configuration
name = "birzeit-lab-scheduler-proxy"
main = "api/proxy.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "*/api/proxy", zone_name = "your-domain.com" }
]
